name: appsen
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  firebase_core: 1.21.1
  firebase_auth: 3.7.0
  cloud_firestore: 3.4.6
  firebase_storage: 10.3.7
  convex_bottom_bar: 3.0.0
  intl: 0.17.0
  geolocator: 9.0.1
  geocoding: 2.0.5
  flutter_launcher_icons: 0.10.0
  flutter: 
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
    

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

